plugins:
- jekyll-remote-theme

remote_theme: "quillie/gh-pages"

title: Wegweistr
description: Notes and Other Stuff Transmitted by Relays

show_downloads: false
show_header: false

icon: icon.png

sass:
    style: compressed
    
